# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{Pratt}
  s.version = "1.6.8"
  s.platform = %q{x86-linux}

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Noel-Hemming"]
  s.date = %q{2010-05-31}
  s.default_executable = %q{pratt}
  s.description = %q{
	  Need a way to keep track of your time, but get caught up in work? Or constant interruptions?
	  Yeah you know who I'm talking about. Those people from the [abc] department always "NEEDING xyz FEATURE NOW!!!".
	  Seriously though. I'm usually just loose track of time. I wanted an app that I could start with a task I think 
	  I'll be working on, but that get's in my face constantly to ensure I'm still working on it. And if I'm not any longer,
	  provides an easy way of changing to another task, or if I have changed tasks and not already updated the app, would 
	  provide an easy way of changing the task of the previously recorded interval. That's what this is intended to do.

	  Time Tracking.
	  Proactively set what you expect to work on.
	  Reactively modify what you are no longer working on.
  }
  s.email = %q{frogstarr78@gmail.com}
  s.executables = ["pratt"]
  s.extra_rdoc_files = [
    "README.html",
     "README.txt",
     "TODO"
  ]
  s.files = [
    ".exrc",
     ".gitignore",
     "History.txt",
     "Manifest.txt",
     "Pratt.gemspec",
     "Pratt.mm",
     "README.html",
     "README.txt",
     "Rakefile",
     "TODO",
     "VERSION",
     "bin/pratt",
     "config.rb",
     "db/sqlite_databases_go_here",
     "db/zips.csv.zip",
     "lib/models.rb",
     "lib/pratt.rb",
     "lib/pratt/core_ext.rb",
     "lib/pratt/core_ext/array.rb",
     "lib/pratt/core_ext/float.rb",
     "lib/pratt/core_ext/nil.rb",
     "lib/pratt/core_ext/numeric.rb",
     "lib/pratt/core_ext/string.rb",
     "lib/pratt/core_ext/time.rb",
     "lib/pratt/dialogs.rb",
     "lib/pratt/formatting.rb",
     "lib/pratt/project_actions.rb",
     "lib/pratt/reports.rb",
     "models/app.rb",
     "models/customer.rb",
     "models/invoice.rb",
     "models/invoice_whence.rb",
     "models/payment.rb",
     "models/pratt.rb",
     "models/project.rb",
     "models/whence.rb",
     "models/zip.rb",
     "pratt.mm",
     "reports/travel.log",
     "reports/travel.log.2009",
     "spec/app_spec.rb",
     "spec/array_spec.rb",
     "spec/customer_spec.rb",
     "spec/fixtures/empty_graph.expectation",
     "spec/fixtures/graph.expectation",
     "spec/fixtures/proportions.expectation",
     "spec/float_spec.rb",
     "spec/formatting_spec.rb",
     "spec/money_spec.rb",
     "spec/nil_class_spec.rb",
     "spec/numeric_spec.rb",
     "spec/payment_spec.rb",
     "spec/pratt_spec.rb",
     "spec/project_spec.rb",
     "spec/rcov.opts",
     "spec/report_action_spec.rb",
     "spec/report_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/string_ext_spec.rb",
     "spec/whence_spec.rb",
     "tasks/pratt.rb",
     "templates/model.eruby",
     "templates/spec.eruby",
     "views/current.eruby",
     "views/general-invoice.eruby",
     "views/graph.eruby",
     "views/invoice.eruby",
     "views/main.rb",
     "views/pid.eruby",
     "views/pop.rb",
     "views/proportions.eruby",
     "views/raw.eruby"
  ]
  s.homepage = %q{http://github.com/frogstarr78/pratt}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{Pratt}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Pro/Re-Active Time Tracker.  Track time based on what you expect to be working on, with frequent prompts to ensure accuracy.}
  s.test_files = [
    "spec/nil_class_spec.rb",
     "spec/whence_spec.rb",
     "spec/array_spec.rb",
     "spec/spec_helper.rb",
     "spec/float_spec.rb",
     "spec/pratt_spec.rb",
     "spec/project_spec.rb",
     "spec/numeric_spec.rb",
     "spec/app_spec.rb",
     "spec/formatting_spec.rb",
     "spec/string_ext_spec.rb",
     "spec/customer_spec.rb",
     "spec/report_spec.rb",
     "spec/money_spec.rb",
     "spec/report_action_spec.rb",
     "spec/payment_spec.rb",
     "spec/rcov.opts",
     "spec/spec.opts",
     "spec/fixtures/empty_graph.expectation",
     "spec/fixtures/proportions.expectation",
     "spec/fixtures/graph.expectation"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["= 1.2.6"])
      s.add_development_dependency(%q<mocha>, ["= 0.9.5"])
      s.add_runtime_dependency(%q<activerecord>, ["= 2.1.1"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, ["= 1.2.4"])
      s.add_runtime_dependency(%q<shifty_week>, ["= 0.1.0"])
      s.add_runtime_dependency(%q<erubis>, ["= 2.6.5"])
      s.add_runtime_dependency(%q<chronic>, ["= 0.2.3"])
      s.add_runtime_dependency(%q<colored>, ["= 1.2"])
    else
      s.add_dependency(%q<rspec>, ["= 1.2.6"])
      s.add_dependency(%q<mocha>, ["= 0.9.5"])
      s.add_dependency(%q<activerecord>, ["= 2.1.1"])
      s.add_dependency(%q<sqlite3-ruby>, ["= 1.2.4"])
      s.add_dependency(%q<shifty_week>, ["= 0.1.0"])
      s.add_dependency(%q<erubis>, ["= 2.6.5"])
      s.add_dependency(%q<chronic>, ["= 0.2.3"])
      s.add_dependency(%q<colored>, ["= 1.2"])
    end
  else
    s.add_dependency(%q<rspec>, ["= 1.2.6"])
    s.add_dependency(%q<mocha>, ["= 0.9.5"])
    s.add_dependency(%q<activerecord>, ["= 2.1.1"])
    s.add_dependency(%q<sqlite3-ruby>, ["= 1.2.4"])
    s.add_dependency(%q<shifty_week>, ["= 0.1.0"])
    s.add_dependency(%q<erubis>, ["= 2.6.5"])
    s.add_dependency(%q<chronic>, ["= 0.2.3"])
    s.add_dependency(%q<colored>, ["= 1.2"])
  end
end

